version: '3.8'

services:
  cassandra-node1:
    build:
      context: .
      args:
        - SSH_KEY_PUB_NAME=${SSH_KEY_PUB_NAME}
        - SUDO_PASSWORD=${SUDO_PASSWORD}
    hostname: cassandra-node1
    ports:
      - "9042:9042"
      - "2201:22"
    environment:
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
      - CASSANDRA_SEEDS=cassandra-node1
    restart: unless-stopped

  cassandra-node2:
      build:
        context: .
        args:
          - SSH_KEY_PUB_NAME=${SSH_KEY_PUB_NAME}
          - SUDO_PASSWORD=${SUDO_PASSWORD}
      hostname: cassandra-node2
      ports:
        - "9043:9042"
        - "2202:22"
      environment:
        - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
        - CASSANDRA_SEEDS=cassandra-node1
      restart: unless-stopped

  cassandra-node3:
      build:
        context: .
        args:
          - SSH_KEY_PUB_NAME=${SSH_KEY_PUB_NAME}
          - SUDO_PASSWORD=${SUDO_PASSWORD}
      hostname: cassandra-node3
      ports:
        - "9044:9042"
        - "2203:22"
      environment:
        - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
        - CASSANDRA_SEEDS=cassandra-node1
      restart: unless-stopped
