version: '3.8'

services:
  # ВМ1 — 192.168.1.197 — "запускает" docker-compose (через монтирование docker.sock)
  vm1:
    container_name: vm1
    build:
      context: .
      dockerfile: vm1/Dockerfile
    networks:
      lab-net:
        ipv4_address: 192.168.1.197
    environment:
      - SSH_USER_PASSWORD=${SSH_USER_PASSWORD}
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Монтируем сокет хоста
    working_dir: /app

  vm2:
    container_name: vm2
    build:
      context: .
      dockerfile: vm2/Dockerfile
    networks:
      lab-net:
        ipv4_address: 192.168.1.198

networks:
  lab-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
